repos:
  - repo: local
    hooks:
      - id: flutter-test
        name: Run Flutter Tests
        entry: flutter test
        language: system
        pass_filenames: false
        stages: [pre-commit]
